seed:
  params:
    seed: $const:seed
  class: starling_ml.modules.processing.runtime.Seed
dataset:
  params:
    factory: starling_ml.modules.data.general.SyntheticDataset
    output: data.dataset
    kwargs:
      task: segmentation
      spatial:
      - 8
      - 8
      seed: 42
  class: starling_ml.modules.processing.runtime.ObjectFactory
batch:
  params:
    dataset: $ctx:data.dataset
    outputs:
      batch.input: input
      batch.target: target
    batch_size: 4
    seed: 42
  class: starling_ml.modules.data.general.BatchSource
model:
  params:
    factory: starling_ml.modules.models.architectures.Segmenter
    output: model.raw
    kwargs:
      classes: 3
      spatial_dims: 2
  class: starling_ml.modules.processing.runtime.ObjectFactory
device:
  params:
    model: $ctx:model.raw
    device: $const:device
    output: model.instance
  class: starling_ml.modules.processing.runtime.PrepareModel
move_input:
  params:
    input: batch.input
    device: $const:device
  class: starling_ml.modules.processing.runtime.MoveToDevice
move_target:
  params:
    input: batch.target
    device: $const:device
  class: starling_ml.modules.processing.runtime.MoveToDevice
forward:
  params:
    model: $ctx:model.instance
    input: batch.input
    output: model.output
  class: starling_ml.modules.forward.Forward
loss:
  params:
    prediction: model.output
    target: batch.target
    output: loss.pointwise
  class: starling_ml.modules.losses.basic.CrossEntropy
dice:
  params:
    prediction: model.output
    target: batch.target
    output: loss.dice
    mode: multiclass
    empty_target: false_positive
  class: starling_ml.modules.losses.overlap.DiceLoss
mix:
  params:
    terms:
    - loss: loss.pointwise
    - loss: loss.dice
  class: starling_ml.modules.losses.combine.LossMixer
optimizer:
  params:
    model: $ctx:model.instance
    lr: 0.001
  class: starling_ml.modules.optimization.OptimizationManager
run:
  params:
    max_steps: $const:max_steps
    defer_finish: true
  class: starling_ml.modules.control.run.RunManager
phase:
  params:
    validate_at_end: true
    validate_every: 2
    validate_at_start: true
  class: starling_ml.modules.control.phase.PhaseManager
train_metrics:
  class: starling_ml.modules.metrics.segmentation.SegmentationMetrics
  params:
    num_classes: 3
    prediction: model.output
    target: batch.target
    mode: multiclass
    prefix: metrics.train
    phase: train
    reset_on: phase_started
    finalize_on: phase_ended
validation_batch:
  class: starling_ml.modules.data.general.BatchSource
  params:
    dataset: $ctx:data.dataset
    outputs:
      validation.input: input
      validation.target: target
    batch_size: 4
    cycle: false
    shuffle: false
    reset_on:
    - validation_start
validation_move_input:
  class: starling_ml.modules.processing.runtime.MoveToDevice
  params:
    input: validation.input
    device: $const:device
validation_move_target:
  class: starling_ml.modules.processing.runtime.MoveToDevice
  params:
    input: validation.target
    device: $const:device
validation_forward:
  class: starling_ml.modules.forward.Forward
  params:
    model: $ctx:model.instance
    input: validation.input
    output: validation.output
    training: false
validation_loss:
  class: starling_ml.modules.losses.overlap.DiceLoss
  params:
    prediction: validation.output
    target: validation.target
    output: validation.loss
    mode: multiclass
    empty_target: false_positive
metrics:
  class: starling_ml.modules.metrics.segmentation.SegmentationMetrics
  params:
    num_classes: 3
    prediction: validation.output
    target: validation.target
    mode: multiclass
